// Tell Google where to find the credentials
process.env.GOOGLE_APPLICATION_CREDENTIALS = './lecture-caption-tool-2fb919185873.json';
const express = require('express');
const cors = require('cors');
const speech = require('@google-cloud/speech');
const app = express();
const port = 3001;

// Allow frontend to talk to backend
app.use(cors());

// This lets the server understand JSON data
app.use(express.json({ limit: '50mb' }));

// Test route
app.get('/api/test', (req, res) => {
  res.json({ message: 'Backend is working!' });
});

// Summary route — frontend will send the transcript here
// and get a summary back. For now it's just a placeholder.
app.post('/api/summary', (req, res) => {
  const { transcript } = req.body;
  res.json({ 
    summary: "Placeholder summary: The lecture covered key topics that were discussed during the session. Later this will be generated by Claude AI." 
  });
});

// Test route to verify Google API works
app.get('/api/test-google', async (req, res) => {
  try {
    const client = new speech.SpeechClient();
    res.json({ message: 'Google Speech-to-Text API connected successfully!' });
  } catch (error) {
    res.status(500).json({ error: 'Failed to connect to Google API', details: error.message });
  }
});

// Route to receive audio and transcribe it
app.post('/api/transcribe', async (req, res) => {
  try {
    const audioBytes = req.body.audio;
    
    // Configure Google Speech-to-Text
    const client = new speech.SpeechClient();
    const audio = {
      content: audioBytes,
    };
    const config = {
      encoding: 'WEBM_OPUS',
      sampleRateHertz: 48000,
      languageCode: 'en-US',
    };
    const request = {
      audio: audio,
      config: config,
    };

    // Send to Google and get transcription
    const [response] = await client.recognize(request);
    console.log('Google response:', JSON.stringify(response, null, 2));
    console.log('Number of results:', response.results ? response.results.length : 0);

    const transcription = response.results
      .map(result => result.alternatives[0].transcript)
      .join(' ');
    
    res.json({ text: transcription });
    
  } catch (error) {
    console.error('Transcription error:', error);
    res.status(500).json({ error: 'Transcription failed', details: error.message });
  }
});

// Start the server
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});