const express = require('express');
const cors = require('cors');
const app = express();
const port = 3001;

// Allow frontend to talk to backend
app.use(cors());

// This lets the server understand JSON data
app.use(express.json());

// Test route
app.get('/api/test', (req, res) => {
  res.json({ message: 'Backend is working!' });
});

// Summary route — frontend will send the transcript here
// and get a summary back. For now it's just a placeholder.
app.post('/api/summary', (req, res) => {
  const { transcript } = req.body;
  res.json({ 
    summary: "Placeholder summary: The lecture covered key topics that were discussed during the session. Later this will be generated by Claude AI." 
  });
});

// Start the server
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});